[jenkins]
jenkins-server ansible_host=3.109.2.128 ansible_user=ubuntu

[kubernetes_master]
master ansible_host=65.2.127.183 ansible_user=ubuntu

[kubernetes_workers]
worker1 ansible_host=15.207.112.199 ansible_user=ubuntu
worker2 ansible_host=35.154.29.166 ansible_user=ubuntu

[all_nodes:children]
jenkins
kubernetes_master
kubernetes_workers
